version: '3.8'

services:
  # 数据库服务
  db:
    image: postgres:13
    container_name: stock_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stock_alerts
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  # 我们的 FastAPI API 服务
  api:
    build: .  # 使用当前目录下的 Dockerfile 来构建镜像
    container_name: stock_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/workspaces/stock_full_stack/app  # 将本地 app 目录挂载到容器中，实现代码热重载
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/stock_alerts
    depends_on:
      - db  # 确保 db 服务先于 api 服务启动

volumes:
  postgres_data: